<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        ?>
        
        <form method="POST">
           Nome <input type="text" name="nome" value="" size="30" />
           <input type="submit" value="enviar" />
        </form>
    </body>
</html>